name: sophie
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  file_picker: ^11.0.2
  flutter_launcher_icons: ^0.14.4
  flutter_timezone: ^5.0.2
  timezone: ^0.11.0
  flutter_markdown_plus: ^1.0.7
  http: ^1.6.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  rrule_generator: ^0.10.1+1
  table_calendar: ^3.2.0
  permission_handler: ^12.0.1
  alarm: ^5.2.1
  home_widget: ^0.9.3
  awesome_notifications: ^0.12.1
  get_it: ^9.2.1
  uuid: ^4.5.3
  collection: ^1.19.1
  rrule: ^0.2.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/bunny.png"
  adaptive_icon_foreground: "assets/bunny.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/
