name: Deploy to apk file

on:
  workflow_dispatch:
    inputs:
      version:
        description: eg. 1.0.0
        required: true
        type: string

      description:
        description: What's new?
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mobile
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up JDK 25
        uses: https://github.com/actions/setup-java@v5
        with:
          java-version: "25"
          distribution: "temurin"
          cache: gradle

      - name: Setup Android SDK
        uses: https://github.com/android-actions/setup-android@v4

      - run: |
          BUILD_NUMBER=$(git rev-list --count HEAD)
          sed -i "s/^version: .*/version: ${{ github.event.inputs.version }}+${BUILD_NUMBER}/" pubspec.yaml

      - name: Set up Flutter
        uses: https://github.com/subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.41.6
          cache: true
          pub-cache: true

      - name: Decode keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/sophie-release.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      - run: flutter build apk --release --target-platform android-arm64
        env:
          KEYSTORE_PATH: sophie-release.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      - run: mv build/app/outputs/flutter-apk/app-release.apk Sophie-${{ github.event.inputs.version }}.apk

      - name: Create tag
        run: |
          git tag -f v${{ github.event.inputs.version }}-android
          git push --force origin v${{ github.event.inputs.version }}-android

      - name: Create Gitea Release
        uses: https://github.com/akkuman/gitea-release-action@v1
        with:
          name: Release ${{ github.event.inputs.version }} (Android)
          tag_name: v${{ github.event.inputs.version }}-android
          body: ${{ github.event.inputs.description }}
          draft: false
          prerelease: false
          files: |
            mobile/Sophie-${{ github.event.inputs.version }}.apk
