services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: tomivagyok
      POSTGRES_DB: sophie
    # volumes:
    #   - pgdata:/var/lib/postgresql
      
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

# volumes:
#   pgdata:
